global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: pulseguard-ingestion
    static_configs:
      - targets: ["ingestion:9101"]
        labels:
          service: ingestion

  - job_name: pulseguard-anomaly-detection
    static_configs:
      - targets: ["anomaly-detection:9102"]
        labels:
          service: anomaly_detection

  - job_name: pulseguard-monitoring
    static_configs:
      - targets: ["monitoring:9103"]
        labels:
          service: monitoring

  - job_name: pulseguard-api
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: api

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
